---
title: "Completion (Number of degrees or awards) regression"
author: "Ahmed"
date: "2/11/2022"
output: 
  pdf_document: 
    keep_tex: yes
classoption: landscape
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
library(fixest)
library(modelsummary)
library(AER)
library(ivreg)
library(bacondecomp) 
library(lmtest) 
library(multiwayvcov) 
library(plm)
library(stargazer)
library(foreign)
library(zoo)
library(lmtest)
library(sandwich)
library(latex2exp)
library(haven)
library(Statamarkdown)
library(devtools) 
library(ggplot2)
library(dplyr)
library(tidyverse)
library(gt)
          

          # ************* CHANGE TO YOUR LOCAL DIRECTORY ***************
load( "~/Desktop/metrics4/IPEDS_files_scraped/project_data/CMT.rdata") #completion_data1, both bachelor and associate sample
load( "~/Desktop/metrics4/IPEDS_files_scraped/project_data/CMT_BACH.rdata") #completion_data_bach 
load( "~/Desktop/metrics4/IPEDS_files_scraped/project_data/CMT_AST.rdata") #completion_data_asso

load("~/Desktop/metrics4/IPEDS_files_scraped/project_data/CMT_STEM.rdata") ## completion_stem, both associate and bachelor sample
load( "~/Desktop/metrics4/IPEDS_files_scraped/project_data/CMT_BACH_STEM.rdata") #completion_bach_stem, by stem dummy
load( "~/Desktop/metrics4/IPEDS_files_scraped/project_data/CMT_AST_STEM.rdata") #completion_ast_stem, by stem dummy

```

```{r echo=F, message=FALSE, warning=FALSE, paged.print=FALSE, results="asis"}

## splitting the policy dummy to short and long terms
#----------------------------------------------------
## this function takes a dataframe, and  
## number of years gap (n) to split a dummy into long, short, mid terms
## the dummy is created within the function

terms_dummy2 <- function(enroll_data,n){
  
enroll_data$rm_st <- ifelse( ((enroll_data$STABBR=="CO" & enroll_data$YEAR >= 2012 & enroll_data$YEAR <= 2012+n)  |
                                            (enroll_data$STABBR=="WA" & enroll_data$YEAR >= 2012 & enroll_data$YEAR <= 2012+n)|
                                            (enroll_data$STABBR=="OR" & enroll_data$YEAR >= 2015 & enroll_data$YEAR <= 2015+n) |
                                            (enroll_data$STABBR=="MA" & enroll_data$YEAR >= 2016 & enroll_data$YEAR <= 2016+n) |
                                            (enroll_data$STABBR=="CA" & enroll_data$YEAR >= 2016 & enroll_data$YEAR <= 2016+n) |
                                            (enroll_data$STABBR=="NV" & enroll_data$YEAR >= 2017 & enroll_data$YEAR <= 2017+n)
                                            )
                                         ,1,0)

enroll_data$rm_lt <- ifelse( ((enroll_data$STABBR=="CO" &  enroll_data$YEAR > 2012+n)  |
                                            (enroll_data$STABBR=="WA" &  enroll_data$YEAR > 2012+n) |
                                            (enroll_data$STABBR=="OR" &  enroll_data$YEAR > 2015+n) |
                                            (enroll_data$STABBR=="MA" &  enroll_data$YEAR > 2016+n) |
                                            (enroll_data$STABBR=="CA" &  enroll_data$YEAR > 2016+n) |
                                            (enroll_data$STABBR=="NV" &  enroll_data$YEAR > 2017+n)
                                            )
                                         ,1,0)

      return(enroll_data)
}

completion_data1 <- terms_dummy2(completion_data1,1) 
completion_data_bach <- terms_dummy2(completion_data_bach,1) 
completion_data_asso <- terms_dummy2(completion_data_asso,1) 

completion_stem <- terms_dummy2(completion_stem,1) 
completion_bach_stem <- terms_dummy2(completion_bach_stem,1) 
completion_ast_stem <- terms_dummy2(completion_ast_stem,1) 



```


\text{ }

```{r echo=F, message=FALSE, warning=FALSE, paged.print=FALSE, results="asis"}

## takes data frame and returns summary stat. table
data_sum <- function(enroll_data_all){
  
    state_treat <- enroll_data_all$STABBR[enroll_data_all$adopt_law==1] %>% unique()
    enroll_data_all$TREAT <- ifelse(enroll_data_all$STABBR %in% state_treat,"RM states","Not RM states" )
  
    df_numerical <- enroll_data_all %>% select(EFTOTLT,FIPS,
                                               per_capita_income,unemply_rate,population,is_large_inst,medical_degree,
                                               is_public_not_prft, is_city,is_aa,ICLEVEL,HLOFFER,TREAT
                                               ) 
    
    df_categorical <- enroll_data_all  %>% select(EFTOTLT,is_large_inst,medical_degree,is_public_not_prft,FIPS,
                                                 is_city,is_aa,ICLEVEL,HLOFFER,UNITID,TREAT,
                                                 COUNTYCD,STABBR,YEAR) 

 
num_sum <- datasummary(
    (`ln total N awards` = EFTOTLT) +
      (`ln per-capita income` = per_capita_income) +
      (`ln population` = population) +
      (`Unemployment rate` = unemply_rate)   ~
              TREAT * (N + Mean + SD + Min + Max),
              data = df_numerical, fmt=3,
    title="Summary statistics by group")

cat_sum0 <- datasummary(
      (`Intitutions or colleges` = UNITID) +
      (`Counties` = COUNTYCD) + 
     (`States` = FIPS) + 
      (`Years` = YEAR)~ TREAT * (NUnique),
              data = df_categorical, 
    title="Summary statistics by group")


cat_sum1 <- datasummary(
      # (`RM dummy-sort term` = adopt_law_st) + ## more than 1000 enrol
      # (`RM dummy-mid term` = adopt_law_mt) +
      # (`RM dummy-long term` = adopt_law_lt) +
    (`Large college dummy` = is_large_inst) + ## more than 1000 enrol
      (`Medical degree dummy` = medical_degree) +
      (`Not private dummy` = is_public_not_prft) +
      (`City location dummy` = is_city)    ~ TREAT * (Mean),
              data = df_categorical, fmt=3,
    title="Summary statistics by group")


cat_sum2 <- datasummary( 
  (`N colleges or institutions` = UNITID) ~ TREAT*ICLEVEL*(NUnique),
            data = df_categorical,
  title="Classification institution’s programs by group")


cat_sum3 <- datasummary(  
  (`N colleges or institutions` = UNITID) ~ TREAT*HLOFFER*(NUnique) ,
            data = df_categorical,
    title="Highest level of offering")


        return( list(num_sum,cat_sum0,cat_sum1,cat_sum2,cat_sum3) )



}

```


## Summary statistics

\text{ }

```{r echo=F, message=FALSE, warning=FALSE, paged.print=FALSE, results="asis"}
## output summary stat

descriptive_stat <- data_sum(completion_data1) ## all completion sample

descriptive_stat[[1]]

```

\text{ }
```{r echo=F, message=FALSE, warning=FALSE, paged.print=FALSE, results="asis"}
## output summary stat
descriptive_stat[[2]]

```


\text{ }
```{r echo=F, message=FALSE, warning=FALSE, paged.print=FALSE, results="asis"}
## output summary stat
descriptive_stat[[3]]

```

\text{ }
```{r echo=F, message=FALSE, warning=FALSE, paged.print=FALSE, results="asis"}
## output summary stat
descriptive_stat[[4]]

```

\text{ }
```{r echo=F, message=FALSE, warning=FALSE, paged.print=FALSE, results="asis"}
## output summary stat
descriptive_stat[[5]]

```

\text{ }


```{r echo=F, message=FALSE, warning=FALSE, paged.print=FALSE, results="asis"}

## run reg and return reg tables
# completion_data1: completion of all undergrad
# completion_data_asso: completion of associate degree
# completion_data_bach: completion of bachelor degree

my_model <- function(completion_data1,completion_data_asso,completion_data_bach){
  
model1 = feols(EFTOTLT ~  adopt_MM+ adopt_law+ per_capita_income  + unemply_rate + population + is_large_inst + medical_degree  +  is_public_not_prft + is_city  + OBEREG  + ICLEVEL + HLOFFER   | 
                COUNTYCD.f + YEAR.f , 
             data = completion_data1)
model01 = summary(model1, cluster = c('UNITID.f'))


model2 <- feols(EFTOTLT ~  adopt_MM +adopt_law+ per_capita_income + unemply_rate + population +is_large_inst + medical_degree   +is_public_not_prft+ is_city   + OBEREG   +ICLEVEL +HLOFFER |
                    COUNTYCD.f + YEAR.f
                          , data = completion_data_asso)
model02 = summary(model2, cluster = c('UNITID.f'))


model3 <- feols(EFTOTLT ~   adopt_MM+ adopt_law +per_capita_income + unemply_rate + population +is_large_inst + medical_degree  +is_public_not_prft+ is_city   + OBEREG   +ICLEVEL +HLOFFER |
                    COUNTYCD.f + YEAR.f
                          , data = completion_data_bach)
model03 = summary(model3, cluster = c('UNITID.f'))


#--------------------------------
num_colleges1 <- completion_data1$UNITID.f %>% unique %>% length %>% as.character
num_colleges2 <- completion_data_asso$UNITID.f %>% unique %>% length %>% as.character
num_colleges3 <- completion_data_bach$UNITID.f %>% unique %>% length %>% as.character

rows <- tribble(~"Coefficients", ~"Model 1",  ~"Model 2",~"Model 3",
                "N college", num_colleges1, num_colleges2,num_colleges3,
                "Year FE", "Y", "Y","Y",
                 "County FE",   "Y","Y","Y", 
                "College covariates",  "Y","Y","Y", 
                "County covariates","Y","Y","Y",
                )


 f <- function(x) format(round(x, 3), big.mark=",")
 
 gm <- tibble::tribble(
  ~raw,        ~clean,          ~fmt,
  "nobs",      "N Obs.",             0,
  "adj.r.squared", paste0("Adjusted ","R<sup>2</sup>"), 2)

#----------------------------------------------------------------
     
models = list(
             "Undergraduate" = model01,
             "Associate" = model02,
             "Bachelor" = model03
             )
var_names <- c(
          'adopt_law' = 'RM' ,
           'adopt_MM'       = 'MM' 
        # 'per_capita_income' = 'ln Per-capita income',
        #      'population' =  'ln Population',
        #            'is_public_not_prft' =  'Not private dummy',
        # 'medical_degree' = "Offers MD",
        #       '(Intercept)' = 'Constant'

      )

modelsummary( models,
              stars = c('*' = .05, '**' = .01,'***' = .001),
              output = "markdown",
              coef_map = var_names,
                gof_map = gm,
              add_rows=rows
             )

}


```


```{r echo=F, message=FALSE, warning=FALSE, paged.print=FALSE, results="asis"}
# long term Vs short term for stem and non stem reg
# completion_data_asso: completion of associate degree
# completion_data_bach: completion of bachelor degree
model_terms_stem2 <- function(completion_data_asso,completion_data_bach){

model2 <- feols(EFTOTLT ~  adopt_MM +adopt_law+ per_capita_income + unemply_rate + population +is_large_inst + medical_degree  + is_public_not_prft+ is_city    + OBEREG   +ICLEVEL +HLOFFER |
                    COUNTYCD.f + YEAR.f
                          , data = completion_data_asso)
model02 = summary(model2, cluster = c('UNITID.f'))

model3 <- feols(EFTOTLT ~   adopt_MM +adopt_law +per_capita_income + unemply_rate + population +is_large_inst + medical_degree  + is_public_not_prft+ is_city   + OBEREG   +ICLEVEL +HLOFFER |
                    COUNTYCD.f + YEAR.f
                          , data = completion_data_bach)
model03 = summary(model3, cluster = c('UNITID.f'))

#--------------------------------
num_colleges2 <- completion_data_asso$UNITID.f %>% unique %>% length %>% as.character
num_colleges3 <- completion_data_bach$UNITID.f %>% unique %>% length %>% as.character

rows <- tribble(~"Coefficients", ~"Model 1",  ~"Model 2",
                "N college",  num_colleges2,num_colleges3,
                "Year FE", "Y", "Y",
                 "County FE",   "Y","Y",
                "College covariates",  "Y","Y",
                "County covariates","Y","Y",
                )


 f <- function(x) format(round(x, 3), big.mark=",")
 
 gm <- tibble::tribble(
  ~raw,        ~clean,          ~fmt,
  "nobs",      "N Obs.",             0,
  "adj.r.squared", paste0("Adjusted ","R<sup>2</sup>"), 2)

#----------------------------------------------------------------
     
models = list(
              "Bachelor-STEM" = model02,
             "Bachelor-Not STEM" = model03
             )
var_names <- c(
          'adopt_law' = 'RM' ,
           'adopt_MM'       = 'MM' 
        # 'per_capita_income' = 'ln Per-capita income',
        #   'population' =  'ln Population',
        #            'is_public_not_prft' =  'Not private dummy',
        # 'medical_degree' = "Offers MD",
        #       '(Intercept)' = 'Constant'

      )

modelsummary( models,
              stars = c('*' = .05, '**' = .01,'***' = .001),
              output = "markdown",
              coef_map = var_names,
                gof_map = gm,
              add_rows=rows
             )


}


```


```{r echo=F, message=FALSE, warning=FALSE, paged.print=FALSE, results="asis"}
# long term Vs short term for stem and non stem reg
# completion_data_asso: completion of associate degree
# completion_data_bach: completion of bachelor degree
model_terms_stem <- function(completion_data_asso,completion_data_bach){

model2 <- feols(EFTOTLT ~  adopt_MM +rm_st  + rm_lt+ per_capita_income + unemply_rate + population +is_large_inst + medical_degree  + is_public_not_prft+ is_city    + OBEREG   +ICLEVEL +HLOFFER |
                    COUNTYCD.f + YEAR.f
                          , data = completion_data_asso)
model02 = summary(model2, cluster = c('UNITID.f'))

model3 <- feols(EFTOTLT ~   adopt_MM+ rm_st  + rm_lt +per_capita_income + unemply_rate + population +is_large_inst + medical_degree  + is_public_not_prft+ is_city   + OBEREG   +ICLEVEL +HLOFFER |
                    COUNTYCD.f + YEAR.f
                          , data = completion_data_bach)
model03 = summary(model3, cluster = c('UNITID.f'))

#--------------------------------
num_colleges2 <- completion_data_asso$UNITID.f %>% unique %>% length %>% as.character
num_colleges3 <- completion_data_bach$UNITID.f %>% unique %>% length %>% as.character

rows <- tribble(~"Coefficients", ~"Model 1",  ~"Model 2",
                "N college",  num_colleges2,num_colleges3,
                "Year FE", "Y", "Y",
                 "County FE",   "Y","Y",
                "College covariates",  "Y","Y",
                "County covariates","Y","Y",
                )


 f <- function(x) format(round(x, 3), big.mark=",")
 
 gm <- tibble::tribble(
  ~raw,        ~clean,          ~fmt,
  "nobs",      "N Obs.",             0,
  "adj.r.squared", paste0("Adjusted ","R<sup>2</sup>"), 2)

#----------------------------------------------------------------
     
models = list(
              "Bachelor-STEM" = model02,
             "Bachelor-Not STEM" = model03
             )
var_names <- c(
          'rm_st' = 'RM12' ,
          'rm_lt' = 'RM3+' ,
           'adopt_MM'       = 'MM' 
        # 'per_capita_income' = 'ln Per-capita income',
        #   'population' =  'ln Population',
        #            'is_public_not_prft' =  'Not private dummy',
        # 'medical_degree' = "Offers MD",
        #       '(Intercept)' = 'Constant'

      )

modelsummary( models,
              stars = c('*' = .05, '**' = .01,'***' = .001),
              output = "markdown",
              coef_map = var_names,
                gof_map = gm,
              add_rows=rows
             )


}


```

```{r echo=F, message=FALSE, warning=FALSE, paged.print=FALSE, results="asis"}
# long term Vs short term all
my_model_terms2 <- function(completion_data1,completion_data_asso,completion_data_bach){

model1 = feols(EFTOTLT ~  adopt_MM+ rm_st  + rm_lt+ per_capita_income  + unemply_rate + population + is_large_inst + medical_degree  +  is_public_not_prft + is_city  + OBEREG + ICLEVEL + HLOFFER   | 
                COUNTYCD.f + YEAR.f , 
             data = completion_data1)
model01 = summary(model1, cluster = c('UNITID.f'))

model2 <- feols(EFTOTLT ~  adopt_MM +rm_st  + rm_lt+ per_capita_income + unemply_rate + population +is_large_inst + medical_degree  + is_public_not_prft+ is_city    + OBEREG   +ICLEVEL +HLOFFER |
                    COUNTYCD.f + YEAR.f
                          , data = completion_data_asso)
model02 = summary(model2, cluster = c('UNITID.f'))

model3 <- feols(EFTOTLT ~   adopt_MM+ rm_st  + rm_lt +per_capita_income + unemply_rate + population +is_large_inst + medical_degree  + is_public_not_prft+ is_city   + OBEREG   +ICLEVEL +HLOFFER |
                    COUNTYCD.f + YEAR.f
                          , data = completion_data_bach)
model03 = summary(model3, cluster = c('UNITID.f'))

#--------------------------------
num_colleges1 <- completion_data1$UNITID.f %>% unique %>% length %>% as.character
num_colleges2 <- completion_data_asso$UNITID.f %>% unique %>% length %>% as.character
num_colleges3 <- completion_data_bach$UNITID.f %>% unique %>% length %>% as.character

rows <- tribble(~"Coefficients", ~"Model 1",  ~"Model 2",~"Model 3",
                "N college", num_colleges1, num_colleges2,num_colleges3,
                "Year FE", "Y", "Y","Y",
                 "County FE",   "Y","Y","Y", 
                "College covariates",  "Y","Y","Y", 
                "County covariates","Y","Y","Y",
                )


 f <- function(x) format(round(x, 3), big.mark=",")
 
 gm <- tibble::tribble(
  ~raw,        ~clean,          ~fmt,
  "nobs",      "N Obs.",             0,
  "adj.r.squared", paste0("Adjusted ","R<sup>2</sup>"), 2)

#----------------------------------------------------------------
     
models = list(
             "Undergraduate" = model01,
             "Associate" = model02,
             "Bachelor" = model03
             )
var_names <- c(
          'rm_st' = 'RM12' ,
          'rm_lt' = 'RM3+' ,
           'adopt_MM'       = 'MM' 
        # 'per_capita_income' = 'ln Per-capita income',
        #   'population' =  'ln Population',
        #            'is_public_not_prft' =  'Not private dummy',
        # 'medical_degree' = "Offers MD",
        #       '(Intercept)' = 'Constant'

      )

modelsummary( models,
              stars = c('*' = .05, '**' = .01,'***' = .001),
              output = "markdown",
              coef_map = var_names,
                gof_map = gm,
              add_rows=rows
             )


}


```


```{r echo=F, message=FALSE, warning=FALSE, paged.print=FALSE, results="asis"}
#****************************
## time trend test regression
#****************************

commonTrendReg <- function(completion_data1,completion_data_asso,completion_data_bach){
  
state_treat <- completion_data1$STABBR[completion_data1$adopt_law==1] %>% unique()

treat_preshock_sample <- function(enroll_data_all){
          pre_policy_df2 <- enroll_data_all %>% filter(adopt_law==0 )
          pre_policy_df2$TREAT <- ifelse(pre_policy_df2$STABBR %in% state_treat,1,0 )
          
          return(pre_policy_df2)
          }

completion_data1 <- treat_preshock_sample(completion_data1)
completion_data_asso <- treat_preshock_sample(completion_data_asso)
completion_data_bach <- treat_preshock_sample(completion_data_bach)
#-------------------------------------------------------------------------
model2 = feols(EFTOTLT ~   TREAT*YEAR + adopt_MM + per_capita_income + is_aa  + unemply_rate + population + is_large_inst + medical_degree   + is_public_not_prft + is_city   + ICLEVEL + HLOFFER  +
                COUNTYCD.f  , 
             data = completion_data1)
model02 = summary(model2, cluster = c('UNITID.f'))


model21 = feols(EFTOTLT ~   TREAT*YEAR + adopt_MM + per_capita_income  + unemply_rate + population + is_large_inst + medical_degree   + is_public_not_prft + is_city   + ICLEVEL + HLOFFER   + COUNTYCD.f
                  , 
             data = completion_data_asso)
model021 = summary(model21, cluster = c('UNITID.f'))

model22 = feols(EFTOTLT ~   TREAT*YEAR + adopt_MM + per_capita_income  + unemply_rate + population + is_large_inst + medical_degree   + is_public_not_prft + is_city   + ICLEVEL + HLOFFER   + COUNTYCD.f
                  , 
             data = completion_data_bach)
model022 = summary(model22, cluster = c('UNITID.f'))


num_colleges21 <- completion_data1$UNITID.f %>% unique %>% length %>% as.character
num_colleges22 <- completion_data_asso$UNITID.f %>% unique %>% length %>% as.character
num_colleges23 <- completion_data_bach$UNITID.f %>% unique %>% length %>% as.character

rows <- tribble(~"Coefficients", ~"Model 1",  ~"Model 2",~"Model 3",
                "N college", num_colleges21, num_colleges22,num_colleges23,
                 "County FE", "Y","Y","Y",
                "College covariates", "Y","Y","Y",
                "County covariates", "Y","Y","Y",
                )
#attr(rows, 'position') <- c(8, 10,11,12,13)


 f <- function(x) format(round(x, 3), big.mark=",")
 

 
 gm <- tibble::tribble(
  ~raw,        ~clean,          ~fmt,
  "nobs",      "N Obs.",             0,
  "adj.r.squared", paste0("Adjusted ","R<sup>2</sup>"), 2)

#----------------------------------------------------------------
     
models = list(
              "Undergraduate" = model02,
             "Associate" = model021,
             "Bachelor" = model022
             )
var_names <- c(
          'TREAT' = 'TREAT' ,
          'YEAR' = 'YEAR' ,
           'TREAT:YEAR'  = 'YEAR*TREAT' 
      )

modelsummary( models,
              stars = c('*' = .05, '**' = .01,'***' = .001),
              output = "markdown",
              coef_map = var_names,
              gof_map = gm,
             add_rows=rows
             )
}


```



```{r echo=F, message=FALSE, warning=FALSE, paged.print=FALSE, results="asis"}
#****************************
## time trend test regression (bachelor-stem and not stem)
#****************************

# "Bachelor-STEM" = completion_data_asso,
#"Bachelor-Not STEM" = completion_data_bach

parl_trend_stem <- function(completion_data_asso,completion_data_bach){
  
state_treat <- completion_data1$STABBR[completion_data1$adopt_law==1] %>% unique()

treat_preshock_sample <- function(enroll_data_all){
          pre_policy_df2 <- enroll_data_all %>% filter(adopt_law==0 )
          pre_policy_df2$TREAT <- ifelse(pre_policy_df2$STABBR %in% state_treat,1,0 )
          
          return(pre_policy_df2)
}

completion_data_asso <- treat_preshock_sample(completion_data_asso)
completion_data_bach <- treat_preshock_sample(completion_data_bach)
#-------------------------------------------------------------------------


model21 = feols(EFTOTLT ~   TREAT*YEAR + adopt_MM + per_capita_income  + unemply_rate + population + is_large_inst + medical_degree   + is_public_not_prft + is_city   + ICLEVEL + HLOFFER   + COUNTYCD.f
                  , 
             data = completion_data_asso)
model021 = summary(model21, cluster = c('UNITID.f'))

model22 = feols(EFTOTLT ~   TREAT*YEAR + adopt_MM + per_capita_income  + unemply_rate + population + is_large_inst + medical_degree   + is_public_not_prft + is_city   + ICLEVEL + HLOFFER   + COUNTYCD.f
                  , 
             data = completion_data_bach)
model022 = summary(model22, cluster = c('UNITID.f'))



num_colleges22 <- completion_data_asso$UNITID.f %>% unique %>% length %>% as.character
num_colleges23 <- completion_data_bach$UNITID.f %>% unique %>% length %>% as.character

rows <- tribble(~"Coefficients", ~"Model 1",  ~"Model 2",
                "N college", num_colleges22,num_colleges23,
                 "County FE", "Y","Y",
                "College covariates", "Y","Y",
                "County covariates", "Y","Y",
                )
#attr(rows, 'position') <- c(8, 10,11,12,13)


 f <- function(x) format(round(x, 3), big.mark=",")
 

 
 gm <- tibble::tribble(
  ~raw,        ~clean,          ~fmt,
  "nobs",      "N Obs.",             0,
  "adj.r.squared", paste0("Adjusted ","R<sup>2</sup>"), 2)

#----------------------------------------------------------------
     
models = list(
              "Bachelor-STEM" = model021,
             "Bachelor-Not STEM" = model022
             )
var_names <- c(
          'TREAT' = 'TREAT' ,
          'YEAR' = 'YEAR' ,
           'TREAT:YEAR'  = 'YEAR*TREAT' 
      )

modelsummary( models,
              stars = c('*' = .05, '**' = .01,'***' = .001),
              output = "markdown",
              coef_map = var_names,
              gof_map = gm,
             add_rows=rows
             )
}


```

\newpage
## Common trend test (N degrees or awards)


```{r echo=F, message=FALSE, warning=FALSE, paged.print=FALSE, results="asis"}
commonTrendReg(completion_data1,completion_data_asso,completion_data_bach)

```




\newpage
## RM effect on N degrees or awards


```{r echo=F, message=FALSE, warning=FALSE, paged.print=FALSE, results="asis"}
my_model(completion_data1,completion_data_asso,completion_data_bach)
```


\newpage

#### Short term Vs long term effect

```{r echo=F, message=FALSE, warning=FALSE, paged.print=FALSE, results="asis"}
my_model_terms2(completion_data1,completion_data_asso,completion_data_bach)
```


\newpage
## Common trend test (NOT STEM)
```{r echo=F, message=FALSE, warning=FALSE, paged.print=FALSE, results="asis"}

parl_trend_stem(
        completion_bach_stem[completion_bach_stem$program_type =="STEM",],
        completion_bach_stem[completion_bach_stem$program_type !="STEM",]
                )

```


\newpage
#### Short term Vs long term effect (STEM)

```{r echo=F, message=FALSE, warning=FALSE, paged.print=FALSE, results="asis"}

model_terms_stem2(
          completion_bach_stem[completion_bach_stem$program_type =="STEM",],
        completion_bach_stem[completion_bach_stem$program_type !="STEM",]
)


```

\newpage
#### Short term Vs long term effect (STEM)

```{r echo=F, message=FALSE, warning=FALSE, paged.print=FALSE, results="asis"}

model_terms_stem(
          completion_bach_stem[completion_bach_stem$program_type =="STEM",],
        completion_bach_stem[completion_bach_stem$program_type !="STEM",]
)


```


