---
title: "Motivation plots"
author: "Ahmed"
date: "3/24/2022"
output: 
  pdf_document: 
    keep_tex: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ivreg)
library(bacondecomp) 
library(lmtest) 
library(multiwayvcov) 
library(plm)
library(stargazer)
library(foreign)
library(zoo)
library(lmtest)
library(sandwich)
library(latex2exp)
library(tidyverse)
library(bookdown)
library(haven)
library(Statamarkdown)
library(devtools) 

library(MatchIt)
library(dplyr)
library(ggplot2)

library(tidyverse)
#library(wonderapi)

# ************* CHANGE TO YOUR LOCAL DIRECTORY ***************
df <- read_csv("~/Desktop/metrics4/project_tables_figures/google_trend/trends_raw.csv")

#---------------------
## begin data cleaning
#----------------------
#"~/Desktop/metrics4/IPEDS_files_scraped/google_trend/trends_raw.csv"


# df %>% colnames()
# df %>% head()

## keeping the year only
df$date <- df$date %>% as.character() %>% substr(.,1,4) %>% as.numeric()

## state abbreviation 
df$state <- substr(df$geo,4,5)

## consider hits less than 1 zero
# df$hits %>% unique()
df$hits[df$hits=="<1"] <- "0"
df$hits <- df$hits %>% as.numeric()

## removing incomplete period 
df <- df %>% filter(date<2022) %>%  
             select(date,state,keyword,hits) %>% 
             aggregate(hits ~ keyword + state + date, data = ., mean)

#-------
## END
#-------
#df %>% summary()

medical_st <- c("AK","DC","OR","WA","NV","HI","CO","VT","MT","RI","NM","MA","CT","NH","IL","NY","MN", "GM",
             "OH","PA", "ND","AR","FL","LA","WV","MO","UT","OK","CA","ME","MD","MI","NJ","AZ","DE")
medical_yr <- c(1998,1998,1998,1998,2000,2000,2000,2014,2014,2007,2007,2012,2012,2013,2013,
  2014,2014,2014,2016,2016,2016,2016,2016,2017,2017,2018,2018,2018,1996,1999,
  2003,2008,2009,2010,2011)

state_info = tibble(state_name = state.name,state=state.abb )
med_marij <- data_frame(
        state = medical_st,
        date_med = medical_yr
) %>% left_join(state_info  )


marij_legal_st <- c("CO","WA","AK","OR","MA","CA","NV","MI")
marij_yr_st <- c(2012,2012,2015,2015,2015,2016,2017,2018)

not_medical_rec_st <- state.abb[!(state.abb %in% c(medical_st,marij_legal_st))]

law_marij <- data_frame(
                        state = marij_legal_st,
                        date_law = marij_yr_st
)



not_mari_or_med <- state.abb[!(state.abb %in% c(medical_st,marij_legal_st) )]

marij_legal_yr <- c(2012,2015,2017,2014,2016,2018)

#df$legal <- ifelse(df$state %in% marij_legal_st ,"Legal_states","Not_legal_states")
df$legal <- ifelse(df$state %in% not_medical_rec_st ,"Not_legal_states","Legal_states")

## spread the data over keywords and take
## the average of marijuana related words
df2 <- df %>% spread(key=keyword,value = hits)

## not necessary referring to dispensary stores
df2$marij_related_words <- rowMeans(df2[,c("marijuana","pot","weed")])

df2 <- df2 %>% select(-c(marijuana,pot,weed)) %>% gather(key=keyword,value =hits,-c(state,date,legal) )

df2 <- df2 %>% left_join(law_marij)

df2$legal[df2$legal!="Legal_states"] <- "NLMR"
df2$legal[df2$legal=="Legal_states"] <- "LMR"


## plot for legal vs not legal
df_groups <- aggregate(hits ~ keyword + legal + date,data=df2,mean)



```


```{r echo=F, message=FALSE, warning=FALSE, paged.print=FALSE, results="asis"}


ggplot( (df2 %>% filter(keyword=="dispensary")),
       aes(x=date, y=hits) ) +
       geom_jitter() +
  #geom_text(aes(label = state), position = position_dodge(0.9))+
       geom_smooth(se = FALSE)+theme_bw()+
  geom_vline(xintercept = marij_yr_st %>% unique, linetype="dashed")+
  xlab("")+
  ylab("Dispensary web popularity")+  scale_x_continuous(breaks = seq(2004,2021,by=2))+
  theme(legend.position=c(.15,.86),legend.title = element_blank())

ggplot( (df_groups %>% filter(keyword=="dispensary")),
        aes(x=date, y=hits, color=legal) )  + 
        geom_smooth(se = FALSE)+theme_bw()+
        geom_vline(xintercept = marij_yr_st %>% unique, linetype="dashed")+
          xlab("")+
        ylab("Dispensary web popularity")+  scale_x_continuous(breaks = seq(2004,2021,by=2))+
       theme(legend.position=c(.15,.86),legend.title = element_blank())



```


```{r echo=F, message=FALSE, warning=FALSE, paged.print=FALSE, results="asis"}

# ************* CHANGE TO YOUR LOCAL DIRECTORY ***************

drug_deaths <- read_tsv("~/Desktop/metrics4/project_tables_figures/drug_deaths_data/d0811.txt") %>% filter(!is.na(Year)) %>% 
  rbind(
read_tsv("~/Desktop/metrics4/project_tables_figures/drug_deaths_data/d1113.txt") %>% filter(!is.na(Year)) 
     ) %>% rbind(
read_tsv("~/Desktop/metrics4/project_tables_figures/drug_deaths_data/d1416.txt") %>% filter(!is.na(Year)) 
                ) %>% rbind(
read_tsv("~/Desktop/metrics4/project_tables_figures/drug_deaths_data/d1719.txt") %>% filter(!is.na(Year))
)


drug_deaths$`Crude Rate` <- drug_deaths$`Crude Rate` %>% as.numeric()
# drug_deaths$deaths_rate_100K <- drug_deaths$Deaths / drug_deaths$Population * 100000
drug_deaths$deaths_rate_100K <- drug_deaths$`Crude Rate`

 drug_deaths$state <- sub('.*,\\s*', '', drug_deaths$County)
 
 drug_deaths$legal <- ifelse(drug_deaths$state %in% marij_legal_st ,"Legal_states","Not_legal_states")
  drug_deaths$legal2 <- ifelse(drug_deaths$state %in% not_medical_rec_st,"Not_legal_states","Legal")
  # drug_deaths$`Five-Year Age Groups Code` %>% unique()
   drug_deaths <- drug_deaths  %>% filter(`Five-Year Age Groups Code` %in% c("25-29", "30-34" , "20-24" ,"15-19"))

 # all: "25-29" "30-34" "35-39" "40-44" "20-24" "15-19"
```


```{r echo=F, message=FALSE, warning=FALSE, paged.print=FALSE, results="asis"}
#+ `Five-Year Age Groups Code`
#drug_deaths_age <-  drug_deaths %>% aggregate(`Crude Rate`~Year+ legal ,data=., FUN = mean)
# drug_deaths_age <-  drug_deaths %>% aggregate(deaths_rate_100K~Year + legal2,data=., FUN = mean) 
# ggplot( drug_deaths_age , aes(x=Year, y=deaths_rate_100K,color=legal2) )  +
#         geom_smooth(se = FALSE)+theme_bw()+
#         geom_vline(xintercept = marij_yr_st %>% unique, linetype="dashed")+
#           xlab("")+
#         ylab("Drug deaths per 100K")+  scale_x_continuous(breaks = seq(2007,2019,by=2))



```


```{r echo=F, message=FALSE, warning=FALSE, paged.print=FALSE, results="asis"}


drug_deaths_age <-  drug_deaths %>% aggregate(deaths_rate_100K~Year + state,data=., FUN = mean) %>% 
  filter(state %in% marij_legal_st )

# 
# ggplot( drug_deaths_age,
#        aes(x=Year, y=deaths_rate_100K) ) +
#        geom_jitter() +
#   geom_text(aes(label = state), position = position_dodge(0.9))+
#        geom_smooth(se = FALSE)+theme_bw()+
#   geom_vline(xintercept = marij_yr_st %>% unique, linetype="dashed")+
#   xlab("")+
#   ylab("Drug deaths per 100K")+  scale_x_continuous(breaks = seq(2007,2019,by=2))

```


```{r echo=F, message=FALSE, warning=FALSE, paged.print=FALSE, results="asis"}

## combining drug deaths with dispensary search data

## aggregate deaths over year and states
drug_deaths_states <-  drug_deaths %>% aggregate(deaths_rate_100K ~ Year + state,data=., FUN = mean) 
 
#drug_deaths_states$legal <- ifelse(drug_deaths_states$state %in% marij_legal_st ,"Legal_states","Not_legal_states")

names(df2)[2] <- "Year"
search_data1 <- df2 %>% filter(keyword == "dispensary" & Year>2007 & Year < 2020) %>% select(-c(date_law,keyword,legal) )

cdc_gogleTrend_data <-  search_data1 %>% left_join(drug_deaths_states) 

cdc_gogleTrend_data$legal <- ifelse(cdc_gogleTrend_data$state %in% marij_legal_st ,"Legal_states","Not_legal_states")


```



```{r echo=F, message=FALSE, warning=FALSE, paged.print=FALSE, results="asis"}
range01 <- function(x){(x-min(x,na.rm = T))/(max(x)-min(x,na.rm = T))} ## rescale google trends to a range of 0 to 1

lcols = c('brown','blue')
linetype = c('solid','dashed')

#cdc_gogleTrend_data$hits <- cdc_gogleTrend_data$hits %>% range01()
#cdc_gogleTrend_data$deaths_rate_100K <- cdc_gogleTrend_data$deaths_rate_100K %>% range01()

coeff1 <-  max(cdc_gogleTrend_data$deaths_rate_100K,na.rm = T) / max(cdc_gogleTrend_data$hits,na.rm = T)

coeff <- 4

# A few constants
temperatureColor <- "#69b3a2"
priceColor <- rgb(0.2, 0.6, 0.9, 1)

dff <- cdc_gogleTrend_data %>% select(state,Year,legal,hits,deaths_rate_100K) %>%  gather(category, value, -c(1:3) )

dff$value[dff$category=="deaths_rate_100K"] <- dff$value[dff$category=="deaths_rate_100K"]/coeff
dff$category[dff$category=="hits"] <- "Dipensary web search"
dff$category[dff$category=="deaths_rate_100K"] <- "Drug death rate per 100K"

# dd=dff[dff$legal=="Legal_states",]
p7 = ggplot(data = dff[dff$legal=="Legal_states",], aes(x=Year, y=value, color=category)) + 
  geom_jitter()+
  stat_smooth(aes(y = value),method = "lm", formula = y ~ x + I(x^2), size = 1,se=F)+
  #geom_smooth(method = "lm", se=F) +
  scale_color_manual(values = lcols) +
  scale_linetype_manual(values = linetype) +
  scale_y_continuous(
    # Features of the first axis
    name = "Dispensary web popularity",
    
    # Add a second axis and specify its features
    sec.axis = sec_axis(~.*coeff, name="Drug deaths per 100K")
  ) + 
  
  theme_bw()  + theme( legend.title = element_blank()) +
  
  ggtitle("Dispensary search and drug deaths") +  scale_x_continuous(breaks = seq(2007,2019,by=2))+
  theme(legend.position=c(.19,.86),legend.title = element_blank())

p7

```



```{r echo=F, message=FALSE, warning=FALSE, paged.print=FALSE, results="asis"}
range01 <- function(x){(x-min(x,na.rm = T))/(max(x)-min(x,na.rm = T))} ## rescale google trends to a range of 0 to 1

lcols = c('brown','blue')
linetype = c('solid','dashed')

#cdc_gogleTrend_data$hits <- cdc_gogleTrend_data$hits %>% range01()
#cdc_gogleTrend_data$deaths_rate_100K <- cdc_gogleTrend_data$deaths_rate_100K %>% range01()

coeff1 <-  max(cdc_gogleTrend_data$deaths_rate_100K,na.rm = T) / max(cdc_gogleTrend_data$hits,na.rm = T)

coeff <- 4

# A few constants
temperatureColor <- "#69b3a2"
priceColor <- rgb(0.2, 0.6, 0.9, 1)

dff <- cdc_gogleTrend_data %>% select(state,Year,legal,hits,deaths_rate_100K) %>%  gather(category, value, -c(1:3) )

dff$value[dff$category=="deaths_rate_100K"] <- dff$value[dff$category=="deaths_rate_100K"]/coeff
dff$category[dff$category=="hits"] <- "Dipensary web search"
dff$category[dff$category=="deaths_rate_100K"] <- "Drug death rate per 100K"

dff %<>% aggregate() 
# dd=dff[dff$legal=="Legal_states",]
p7 = ggplot(data = dff, aes(x=Year, y=value, color=category)) + 
 # geom_jitter()+
  #stat_smooth(aes(y = value),method = "lm", formula = y ~ x + I(x^2), size = 1,se=F)+
  geom_smooth(method = "lm", se=F) +
  scale_color_manual(values = lcols) +
  scale_linetype_manual(values = linetype) +
  scale_y_continuous(
    # Features of the first axis
    name = "Dispensary web popularity",
    
    # Add a second axis and specify its features
    sec.axis = sec_axis(~.*coeff, name="Drug deaths per 100K")
  ) + 
  
  theme_bw()  + theme( legend.title = element_blank()) +
  
  ggtitle("Dispensary search and drug deaths") +  scale_x_continuous(breaks = seq(2007,2019,by=2))+
  theme(legend.position=c(.19,.86),legend.title = element_blank())

p7

```

```{r echo=F, message=FALSE, warning=FALSE, paged.print=FALSE, results="asis"}

cdc_gogleTrend_data2 = cdc_gogleTrend_data %>%  gather(category, value, -c(1:2,5) )
cdc_gogleTrend_data2$type <- paste0(cdc_gogleTrend_data2$legal,"_",cdc_gogleTrend_data2$category)

ggplot( cdc_gogleTrend_data2[cdc_gogleTrend_data2$category=="deaths_rate_100K",] ,
       aes(x=Year, y=value) ) +
       geom_jitter() +
  #geom_text(aes(label = state), position = position_dodge(0.9))+
       geom_smooth(method = "lm",se = FALSE)+theme_bw()+
  geom_vline(xintercept = marij_yr_st %>% unique, linetype="dashed")+
  xlab("")+
  ylab("Drug death rate per 100K")+  scale_x_continuous(breaks = seq(2004,2021,by=2))+
  theme(legend.position=c(.15,.86),legend.title = element_blank())

ggplot( cdc_gogleTrend_data2,
        aes(x=Year, y=value, color=category) )  + 
        geom_smooth(method = "lm",se = FALSE)+theme_bw()+
        geom_vline(xintercept = marij_yr_st %>% unique, linetype="dashed")+
          xlab("")+
        ylab("Dispensary web popularity")+  scale_x_continuous(breaks = seq(2004,2021,by=2))+
       theme(legend.position=c(.15,.86),legend.title = element_blank())

 

```

